<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>학생 등록</title>
</head>
<body>
	<form action="<%=request.getContextPath() %>/student/insert" method="post">
		<table>
			<tr>
				<td>학생번호</td>
				<td><input type="text" name="studentNo" required></td>
			</tr>
			<tr>
				<td>학과번호</td>
				<td>
					<select name="departmentNo" style="width: 177px; height: 22px">
						<option>001</option>
						<option>002</option>
						<option>003</option>
						<option>004</option>
						<option>005</option>
						<option>006</option>
						<option>007</option>
						<option>008</option>
						<option>009</option>
						<option>010</option>
						<option>011</option>
						<option>012</option>
						<option>013</option>
						<option>014</option>
						<option>015</option>
						<option>016</option>
						<option>017</option>
						<option>018</option>
						<option>019</option>
						<option>020</option>
						<option>021</option>
						<option>022</option>
						<option>023</option>
						<option>024</option>
						<option>025</option>
						<option>026</option>
						<option>027</option>
						<option>028</option>
						<option>029</option>
						<option>030</option>
						<option>031</option>
						<option>032</option>
						<option>033</option>
						<option>034</option>
						<option>035</option>
						<option>036</option>
						<option>037</option>
						<option>038</option>
						<option>039</option>
						<option>040</option>
						<option>041</option>
						<option>042</option>
						<option>043</option>
						<option>044</option>
						<option>045</option>
						<option>046</option>
						<option>047</option>
						<option>048</option>
						<option>049</option>
						<option>050</option>
						<option>051</option>
						<option>052</option>
						<option>053</option>
						<option>054</option>
						<option>055</option>
						<option>056</option>
						<option>057</option>
						<option>058</option>
						<option>059</option>
						<option>060</option>
						<option>061</option>
						<option>062</option>
						<option>063</option>
					</select>
				</td>
			</tr>
			<tr>
				<td>학생이름</td>
				<td><input type="text" name="studentName" required></td>
			</tr>
			<tr>
				<td>학생주민번호</td>
				<td><input type="text" name="studentSsn" required></td>
			</tr>
			<tr>
				<td>학생주소</td>
				<td><input type="text" name="studentAddress" required></td>
			</tr>
			<tr>
				<td>입학일자</td>
				<td><input type="text" name="entranceDate" required></td>
			</tr>
			<tr>
				<td>휴학유무</td>
				<td>
					<select name="absenceYn" style="width: 177px; height: 22px">
						<option>Y</option>
						<option selected>N</option>
					</select>
				</td>
			</tr>
			<tr>
				<td>지도교수번호</td>
				<td>
					<select name="coachProfessorNo" style="width: 177px; height: 22px">
						<option>P001</option>
						<option>P002</option>
						<option>P003</option>
						<option>P004</option>
						<option>P005</option>
						<option>P006</option>
						<option>P007</option>
						<option>P008</option>
						<option>P009</option>
						<option>P010</option>
						<option>P011</option>
						<option>P012</option>
						<option>P013</option>
						<option>P014</option>
						<option>P015</option>
						<option>P016</option>
						<option>P017</option>
						<option>P018</option>
						<option>P019</option>
						<option>P020</option>
						<option>P021</option>
						<option>P022</option>
						<option>P023</option>
						<option>P024</option>
						<option>P025</option>
						<option>P026</option>
						<option>P027</option>
						<option>P028</option>
						<option>P029</option>
						<option>P030</option>
						<option>P031</option>
						<option>P032</option>
						<option>P033</option>
						<option>P034</option>
						<option>P035</option>
						<option>P036</option>
						<option>P037</option>
						<option>P038</option>
						<option>P039</option>
						<option>P040</option>
						<option>P041</option>
						<option>P042</option>
						<option>P043</option>
						<option>P044</option>
						<option>P045</option>
						<option>P046</option>
						<option>P047</option>
						<option>P048</option>
						<option>P049</option>
						<option>P050</option>
						<option>P051</option>
						<option>P052</option>
						<option>P053</option>
						<option>P054</option>
						<option>P055</option>
						<option>P056</option>
						<option>P057</option>
						<option>P058</option>
						<option>P059</option>
						<option>P060</option>
						<option>P061</option>
						<option>P062</option>
						<option>P063</option>
						<option>P064</option>
						<option>P065</option>
						<option>P066</option>
						<option>P067</option>
						<option>P068</option>
						<option>P069</option>
						<option>P070</option>
						<option>P071</option>
						<option>P072</option>
						<option>P073</option>
						<option>P074</option>
						<option>P075</option>
						<option>P076</option>
						<option>P077</option>
						<option>P078</option>
						<option>P079</option>
						<option>P080</option>
						<option>P081</option>
						<option>P082</option>
						<option>P083</option>
						<option>P084</option>
						<option>P085</option>
						<option>P086</option>
						<option>P087</option>
						<option>P088</option>
						<option>P089</option>
						<option>P090</option>
						<option>P091</option>
						<option>P092</option>
						<option>P093</option>
						<option>P094</option>
						<option>P095</option>
						<option>P096</option>
						<option>P097</option>
						<option>P098</option>
						<option>P099</option>
						<option>P100</option>
						<option>P101</option>
						<option>P102</option>
						<option>P103</option>
						<option>P104</option>
						<option>P105</option>
						<option>P106</option>
						<option>P107</option>
						<option>P108</option>
						<option>P109</option>
						<option>P110</option>
						<option>P111</option>
						<option>P112</option>
						<option>P113</option>
						<option>P114</option>
					</select>
				</td>
			</tr>
			<tr>
				<td><button type="reset">초기화</button>
				<button type="submit">등록</button></td>
			</tr>
		</table>
	</form>
</body>
</html>